### ISSUE TITLE
🐛 [BUG] - Serialization should be deterministic

### ISSUE THREAD

**Issue by OliverKunc** [dlr-gtlab/gtlab-core#1291]
### Summary

Saving a project can lead to changes of XML serializations of objects that were not changed. These XML changes are due to different ordering of the tag attributes.

### Expected Behaviour

Unchanged objects should have constant serialization.

### Reproduction steps

```bash
Not always reproducible, but occurs quite often.

- Commit a project to a git repository
- Change some little thing, e.g. some property of an object
- Save the project
- git diff
```

### Screenshots

![grafik](https://github.com/user-attachments/assets/2b4982ff-dd77-45b2-8497-144524263359)

### GTlab environment

```bash
GTlab Version: 2.0.9
```

### OS

Windows

**Comment by rainman110** [comment]
@OliverKunc you are right, the error is the "false" flag in the first line of
https://github.com/dlr-gtlab/gtlab-core/blob/542e47d4adab337f7c6e7558508b882b719626fc/src/core/process_management/gt_taskgroup.cpp#L503-L507

🤦

**Comment by OliverKunc** [comment]
I am glad this is an easy fix :-)

**Comment by rainman110** [comment]
> Side-question: is there any use case for the "false" flag?

This is the normal "qt" behaviour and is much faster, since we don't need to sort the elements. XML does not define an element order as far as i know, so this behaviour is valid.

It makes sense to use it, when we are not storing objects to disk but simply transfer them via an xml bytestream over a network connection.
