### ISSUE TITLE
Allow to detach MDI Tabs to make them their own standalone widget

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#604]
In GitLab by @mariusalexander on Oct 4, 2023, 15:59

Similar to brwoser tabs they can be moved to a standalone window. This would enhance the user experience quite a bit IMO and would allow for a more productive and less clunky user experience. Obviously when closing GTlab all detached tabs should be closed as well (and maybe the user should be informed that there are open tabs?)

**Comment by rainman110** [comment]
Related to #610. @mariusalexander Could you estimate, how much work this will be?

**Comment by mariusalexander** [comment]
See PR #1201 for more details. I gave it a shot, but it took more time/was more complicated than I expected. This is mainly related to the unclear ownership of mdi items and widgets (see #1199), which I had not the patience to dive into. 

Another issue is, how will we allow the widget to redock. **This should be discussed.**

Since this is a feature request and not a bug fix, I will move this to 2-1-0. I will also unassign myself for now.

**Comment by mariusalexander** [comment]
See #1210 for more details, this will be implemented for the 2-0-7 release 🎉
