### ISSUE TITLE
Discussion how to cleanup error logging and inform user

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#611]
In GitLab by @bjoernTWK on Nov 6, 2023, 10:55

## What is the purpose of the change?
- If a process is running in which a parametric study calls a invalid process again and again, the user cannot stop the process due to the error message pop-up-window.
- Example given: a parameteric study in the performance in that a invalid expression is placed

## Which tasks have to be performed?
- [ ] Maybe it would be better to allow to focus the main window again so that an process interruption is possible.

**Comment by jensschmeink** [comment]
@mariusalexander I think this is still a problem if the widget is not turned of, isn't it?

**Comment by jensschmeink** [comment]
@mariusalexander I searched for an option to make the dialog non modal but you use the exec() function in a complex function to show the dialog. To see it in a non modal way I would need to use the show() function but it is not possible in the current implementation

**Comment by mariusalexander** [comment]
I think wie have three options:

1. Since appearently everybody disables this widget anyways we could simply remove it. Then #531 can be closed as well.
2. we could reimplement the widget from scratch, take the time to do it right
3. we remove it and implementiert an alternative way to inform the user about an error. This could be a button in the toolbar that appears on an aerror and that draws the attention of the user. Or a floating panel somewhere that shows the first few errors

**Comment by jensschmeink** [comment]
@mariusalexander I like your ideas. I'll set this issue on the lists of elements to discuss

**Comment by jensschmeink** [comment]
Current solution will be to remove the dialog. 
For long term enhancement of logging tasks should have the possibility to set a kind of logging level as tasks are the main reason for annoying messages

**Comment by jensschmeink** [comment]
Sorry, that was just a fast written note while a meeting.
One of the main reasons for frustration is the appearance of the dialog while large tasks are running (e.g. parametric studies).  
Because of this it might be a helpful implementation to enable tasks to change the logging of its calculators to be silent.

**Comment by mariusalexander** [comment]
I see. However, I would imagine that this is difficult to implement. Nevertheless, should we create a separate issue for removing the error widget or should I just create a PR?

**Comment by jensschmeink** [comment]
> I see. However, I would imagine that this is difficult to implement. Nevertheless, should we create a separate issue for removing the error widget or should I just create a PR?

You can just open an PR but keep this issue open for further discussion
