### ISSUE TITLE
Unknown Task not shown

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#612]
In GitLab by @jensschmeink on Nov 6, 2023, 11:13

While unknown calculator classes are represented in GTlab by a red line in the process view (see pic) unknwon task are not read at all and therefore not displayed.   
![grafik](https://my-gitlab-bucket.s3.amazonaws.com/727352741/53fd9392750a3499e8727808e061133a9f6d5ddca443aedf363187385eb6427c/grafik.png)  
The logging says "invalid task file"

**Comment by rainman110** [comment]
@NitenIchiry Please ask @jensschmeink  who wrote this issue (I just converted it to github)

**Comment by jensschmeink** [comment]
> @rainman110 I do not 100% understand how to reproduce this issue (i cannot see your grafik). ![bug](https://private-user-images.githubusercontent.com/73160642/357428300-c05fd4a0-4431-4826-b815-79cd1fe22a40.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTYwMDYsIm5iZiI6MTcyMzYxNTcwNiwicGF0aCI6Ii83MzE2MDY0Mi8zNTc0MjgzMDAtYzA1ZmQ0YTAtNDQzMS00ODI2LWI4MTUtNzljZDFmZTIyYTQwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NTYyYTZkZjcyNDFhNjg2NDFkYTgwZDU4Zjg5OGQ5MmVlMjJlMDgzOTdiZTIwNGQ5OTdlN2JkZjJhYzIxMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPauESjQok-C0V699G3bxpLUQBs-m_8gRmQ6cQVLh8M) How do you reproduce this ? Do I need a special type of task ? What module needs to be missing for invalid tasks to get your logging ?

@NitenIchiry you may use the Python-Module and add a python task and then restart GTlab without the python module.

**Comment by NitenIchiry** [comment]
What I found out this far:
- GtPyTasks are recognized as dummy tasks
- When GtTaskGroup loops through active tasks also the dummy object of GtPyTask is run through and because it cannot be cast to GtTask an error is printed for an unknown file

@rainman110 would you recommend to check at this point, while looping though the tasks, whether the object is a dummy and then create a red task object which says this is unknown ? Does this normally work automatically with all other datamodel classes ? It also works with calculators as we can see. I am not that deep in yet, so i could have a longer look. But maybe you have an opinion on this.
